[context.production]
  command = "APP_ENV=production API_URL=$PROD_API_URL KEYCLOAK_URL=$PROD_KEYCLOAK_URL KEYCLOAK_REALM=$PROD_KEYCLOAK_REALM KEYCLOAK_CLIENT_ID=$PROD_KEYCLOAK_CLIENT_ID KEYCLOAK_REDIRECT_URI=$PROD_KEYCLOAK_REDIRECT_URI npm run dist"

[context.develop]
  command = "APP_ENV=staging API_URL=$STAGING_API_URL KEYCLOAK_URL=$STAGING_KEYCLOAK_URL KEYCLOAK_REALM=$STAGING_KEYCLOAK_REALM KEYCLOAK_CLIENT_ID=$STAGING_KEYCLOAK_CLIENT_ID KEYCLOAK_REDIRECT_URI=$STAGING_KEYCLOAK_REDIRECT_URI npm run dist"

[context.deploy-preview]
  command = "APP_ENV=staging API_URL=$STAGING_API_URL KEYCLOAK_URL=$STAGING_KEYCLOAK_URL KEYCLOAK_REALM=$STAGING_KEYCLOAK_REALM KEYCLOAK_CLIENT_ID=$STAGING_KEYCLOAK_CLIENT_ID KEYCLOAK_REDIRECT_URI=$DEPLOY_PRIME_URL npm run dist"
